# Generated by Django 4.0.4 on 2022-05-16 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotas',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='favor', to=settings.AUTH_USER_MODEL),
        ),
    ]
