# Generated by Django 4.0.4 on 2022-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_quotas_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotas',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='quotas',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
