# Generated by Django 4.0.4 on 2022-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_quotas_download_quotas_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotas',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
