# Generated by Django 4.0.4 on 2022-05-22 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap', '0005_messege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send', to=settings.AUTH_USER_MODEL),
        ),
    ]
