# Generated by Django 4.0.4 on 2022-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_usersphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersphotos',
            name='comment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersphotos',
            name='image',
            field=models.ImageField(upload_to='users_photos_media'),
        ),
    ]
