# Generated by Django 4.0.4 on 2022-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_alter_usersphotos_comment_alter_usersphotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersphotos',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='usersphotos',
            name='is_main',
            field=models.BooleanField(null=True),
        ),
    ]
