# Generated by Django 4.0.4 on 2022-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_alter_usersphotos_image_alter_usersphotos_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersphotos',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
