# Generated by Django 4.0.4 on 2022-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_alter_usersphotos_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='messege',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messege',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
