# Generated by Django 4.0.4 on 2022-05-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_alter_messege_messege_alter_messege_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messege',
            old_name='picture',
            new_name='nkar',
        ),
    ]
