# Generated by Django 4.0.4 on 2022-05-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0012_rename_picture_messege_nkar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege',
            name='nkar',
        ),
    ]
