# Generated by Django 4.0.4 on 2022-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0013_remove_messege_nkar'),
    ]

    operations = [
        migrations.AddField(
            model_name='messege',
            name='nkar',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
