# Generated by Django 4.0.4 on 2022-05-31 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap', '0014_messege_nkar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('friend_reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_r', to=settings.AUTH_USER_MODEL)),
                ('friend_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
